/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hotel_Reservation_System;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ukasha Gamer
 */
public class AccountInfo extends javax.swing.JFrame {

    private String userEmail; // or private int userId;

    /**
     * Creates new form MyAccounts
     */
    public AccountInfo(String email) {
        this.userEmail = email;
        initComponents();
        // Fetch and display user data
        loadUserData();
    }

    public AccountInfo() {
        initComponents();
        // Retrieve email from UserEmailSession if not provided
        this.userEmail = UserEmailSession.getInstance().getUserEmail();
        loadUserData();
    }

    // Example method to fetch and display user data
    private void loadUserData() {
        if (userEmail == null || userEmail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No email provided.");
            return;
        }
        try {
            Connection con = DBConnection.getConnection();
            String query = "SELECT * FROM users WHERE email = ?";  // or "WHERE user_id = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, userEmail); // or pst.setInt(1, userId);

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String firstName = rs.getString("first_name");
                String lastName = rs.getString("last_name");
                String phoneNo = rs.getString("phone_no");
                String email = rs.getString("email");
                String nationality = rs.getString("nationality");
                String password = rs.getString("password");

                // Display data on the Account Info page labels
                frstNametxt.setText(firstName);

                lastNametxt.setText(lastName);
                phonenotxt.setText(phoneNo);
                emailtxt.setText(email);
                nationalitytxt.setText(nationality);
                pswrdtxt.setText(password);  // Display the password
            }

            rs.close();
            pst.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void enableEditing(boolean enable) {
        frstNametxt.setEditable(enable);

        lastNametxt.setEditable(enable);
        phonenotxt.setEditable(enable);
        emailtxt.setEditable(enable);
        nationalitytxt.setEditable(enable);
        pswrdtxt.setEditable(enable);  // Enable password field for editing

        savebtn.setVisible(enable);
    }

    private void saveUserData() {
        String updatedFirstName = frstNametxt.getText();
        String updatedLastName = lastNametxt.getText();
        String updatedPhoneNo = phonenotxt.getText();
        String updatedEmail = emailtxt.getText();
        String updatedNationality = nationalitytxt.getText();
        String updatedPassword = pswrdtxt.getText();  // Get the updated password

        try {
            Connection con = DBConnection.getConnection();
            String query = "UPDATE users SET first_name = ?, last_name = ?, phone_no = ?, email = ?, nationality = ?, password = ? WHERE email = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, updatedFirstName);
            pst.setString(2, updatedLastName);
            pst.setString(3, updatedPhoneNo);
            pst.setString(4, updatedEmail);
            pst.setString(5, updatedNationality);
            pst.setString(6, updatedPassword);
            pst.setString(7, userEmail);  // Use userEmail as the identifier for the update

            int rowsAffected = pst.executeUpdate();
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "User information updated successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update user information.");
            }

            pst.close();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nationalitytxt = new app.bolivia.swing.JCTextField();
        frstNametxt = new app.bolivia.swing.JCTextField();
        lastNametxt = new app.bolivia.swing.JCTextField();
        emailtxt = new app.bolivia.swing.JCTextField();
        pswrdtxt = new app.bolivia.swing.JCTextField();
        phonenotxt = new app.bolivia.swing.JCTextField();
        savebtn = new necesario.RSMaterialButtonCircle();
        editbtn = new necesario.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 240, 230));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(51, 0, 0));
        jPanel4.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel9.setText(" ");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, -1));

        jPanel4.add(jPanel6);
        jPanel6.setBounds(0, 0, 70, 48);

        jLabel11.setText("jLabel3");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(17304, 123, 348, 26);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("X");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel12);
        jLabel12.setBounds(1330, 0, 38, 30);

        jLabel13.setFont(new java.awt.Font("Stencil", 1, 40)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Account Information ");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(340, 70, 510, 60);

        jLabel14.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("- Your personal and contact details");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(580, 130, 290, 27);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6);
        jLabel6.setBounds(998, 0, 30, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 1600, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profile.png"))); // NOI18N
        jLabel1.setText(" ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 240, 290, 320);

        jPanel10.setBackground(new java.awt.Color(139, 69, 19));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10);
        jPanel10.setBounds(0, 590, 1040, 10);

        jPanel9.setBackground(new java.awt.Color(139, 69, 19));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(1020, 220, 20, 370);

        jPanel11.setBackground(new java.awt.Color(139, 69, 19));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11);
        jPanel11.setBounds(0, 220, 1040, 10);

        jPanel12.setBackground(new java.awt.Color(139, 69, 19));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel12);
        jPanel12.setBounds(0, 230, 10, 370);

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel15.setText(" First Name:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(340, 240, 130, 40);

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel17.setText("Last Name: ");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(350, 300, 130, 22);

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel18.setText("Phone No:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(350, 470, 100, 30);

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel16.setText("Password: ");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(350, 420, 100, 22);

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel19.setText("Nationality:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(350, 530, 120, 30);

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        jLabel20.setText(" Email:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(350, 360, 70, 22);

        nationalitytxt.setEditable(false);
        nationalitytxt.setText(" ");
        nationalitytxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        nationalitytxt.setPlaceholder("Nationality");
        nationalitytxt.setSelectionColor(new java.awt.Color(153, 0, 0));
        jPanel1.add(nationalitytxt);
        nationalitytxt.setBounds(510, 530, 300, 40);

        frstNametxt.setEditable(false);
        frstNametxt.setText(" ");
        frstNametxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        frstNametxt.setPlaceholder(" First Name");
        frstNametxt.setSelectionColor(new java.awt.Color(153, 0, 0));
        jPanel1.add(frstNametxt);
        frstNametxt.setBounds(510, 240, 300, 40);

        lastNametxt.setEditable(false);
        lastNametxt.setText(" ");
        lastNametxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        lastNametxt.setPlaceholder("Last Name");
        lastNametxt.setSelectionColor(new java.awt.Color(153, 0, 0));
        jPanel1.add(lastNametxt);
        lastNametxt.setBounds(510, 290, 300, 40);

        emailtxt.setEditable(false);
        emailtxt.setText(" ");
        emailtxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        emailtxt.setPlaceholder(" Email");
        emailtxt.setSelectionColor(new java.awt.Color(153, 0, 0));
        jPanel1.add(emailtxt);
        emailtxt.setBounds(510, 350, 300, 40);

        pswrdtxt.setEditable(false);
        pswrdtxt.setText(" ");
        pswrdtxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        pswrdtxt.setPlaceholder("Password");
        pswrdtxt.setSelectionColor(new java.awt.Color(153, 0, 0));
        jPanel1.add(pswrdtxt);
        pswrdtxt.setBounds(510, 410, 300, 40);

        phonenotxt.setEditable(false);
        phonenotxt.setText(" ");
        phonenotxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        phonenotxt.setPlaceholder("Phone No");
        phonenotxt.setSelectionColor(new java.awt.Color(153, 0, 0));
        jPanel1.add(phonenotxt);
        phonenotxt.setBounds(510, 470, 300, 40);

        savebtn.setBackground(new java.awt.Color(78, 52, 46));
        savebtn.setText("Save");
        savebtn.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        jPanel1.add(savebtn);
        savebtn.setBounds(910, 530, 100, 50);

        editbtn.setBackground(new java.awt.Color(78, 52, 46));
        editbtn.setText("Edit");
        editbtn.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });
        jPanel1.add(editbtn);
        editbtn.setBounds(850, 490, 110, 50);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1584, 752));

        setSize(new java.awt.Dimension(1033, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        DashBoard dash = new DashBoard();
        dash.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        // System.exit(0);
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jLabel6MouseClicked

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
        saveUserData();  // Save edited data to the database
    }//GEN-LAST:event_savebtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        // Display a dialog box to inform the user that they can edit their info
        JOptionPane.showMessageDialog(null, "You can now edit your account information.");
        enableEditing(true);  // Enable editing of the fields
    }//GEN-LAST:event_editbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.RSMaterialButtonCircle editbtn;
    private app.bolivia.swing.JCTextField emailtxt;
    private app.bolivia.swing.JCTextField frstNametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private app.bolivia.swing.JCTextField lastNametxt;
    private app.bolivia.swing.JCTextField nationalitytxt;
    private app.bolivia.swing.JCTextField phonenotxt;
    private app.bolivia.swing.JCTextField pswrdtxt;
    private necesario.RSMaterialButtonCircle savebtn;
    // End of variables declaration//GEN-END:variables
}
