/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hotel_Reservation_System;

import java.sql.Connection;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;

/**
 *
 * @author Ukasha Gamer
 */
public class MakeReservations extends javax.swing.JFrame {

     
    private String roomNumber;
    private String roomType;

    /**
     * Creates new form Makereservations
     */
    public MakeReservations(String roomNumber, String roomType) {
        this.roomNumber = roomNumber;
        this.roomType = roomType;
        initComponents();
        setRoomDetails(roomNumber, roomType);

    }

    public MakeReservations() {
        initComponents();
    }

    private void setRoomDetails(String roomNumber  , String roomType ) {
        roomnotxt1.setText( roomNumber ); // Display room number
        roomtypetxt.setText(roomType); // Display room type
    }

    // Validates the reservation fields 
    private boolean validateReservationFields() {
        if (CustomerNametxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the customer name.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (Checkin.getDatoFecha() == null) {
            JOptionPane.showMessageDialog(this, "Please select a check-in date.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (Checkkkout.getDatoFecha() == null) {
            JOptionPane.showMessageDialog(this, "Please select a check-out date.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (roomnotxt1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a room number.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (roomtypetxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a room type.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    private long getNumberOfNights() {
        LocalDate checkInDate = Checkin.getDatoFecha().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate checkOutDate = Checkkkout.getDatoFecha().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        return ChronoUnit.DAYS.between(checkInDate, checkOutDate);
    }

    private double getPricePerNight(String roomType) {
        double pricePerNight = 0.0;
        String query = "SELECT price_per_night FROM rooms WHERE room_type = ? AND availability_status = 'Available' LIMIT 1";

        try (
                Connection con = DBConnection.getConnection(); PreparedStatement pst = con.prepareStatement(query)) {

            // Set the parameter for the room type
            pst.setString(1, roomType);

            // Execute the query and process the result
            try (ResultSet rs = pst.executeQuery()) {
                if (rs.next()) {
                    pricePerNight = rs.getDouble("price_per_night");
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }

        return pricePerNight;
    }

    private void calculateTotalPrice() {
        if (!validateReservationFields()) {
            return; // Ensure fields are valid before calculation
        }
        String roomType = roomtypetxt.getText().trim();

        long numberOfNights = getNumberOfNights();
        double pricePerNight = getPricePerNight(roomType);

        double totalPrice = pricePerNight * numberOfNights;

        totalStayPricetxt.setText(String.format("PKR %.2f", totalPrice));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalStayPricetxt = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Checkkkout = new rojeru_san.componentes.RSDateChooser();
        Checkin = new rojeru_san.componentes.RSDateChooser();
        ReserveRoom = new necesario.RSMaterialButtonCircle();
        ComputeTotalbtn = new necesario.RSMaterialButtonCircle();
        CustomerNametxt = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        roomtypetxt = new app.bolivia.swing.JCTextField();
        roomnotxt1 = new app.bolivia.swing.JCTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 240, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gettyimages-1430548900-612x6122.jpg"))); // NOI18N
        jLabel4.setText(" ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 610, 410));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1368, 30));

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reserve Your Stay");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 430, 60));

        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2285, 123, 348, 26));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("- Book Now for a Comfortable Experience");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 360, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 38, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel2.setText(" ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 60, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1368, 200));

        totalStayPricetxt.setText(" ");
        totalStayPricetxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        totalStayPricetxt.setPlaceholder(" ");
        totalStayPricetxt.setSelectionColor(new java.awt.Color(153, 0, 0));
        jPanel1.add(totalStayPricetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 320, 40));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel7.setText("Customer Name :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 150, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel8.setText("Check-out Date:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 150, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel9.setText("Check-in Date: ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 150, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel10.setText("Room Type:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 150, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel11.setText("Room No:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 150, -1));

        Checkkkout.setBackground(new java.awt.Color(140, 140, 140));
        Checkkkout.setColorBackground(new java.awt.Color(153, 0, 0));
        Checkkkout.setColorButtonHover(new java.awt.Color(153, 0, 0));
        Checkkkout.setColorForeground(new java.awt.Color(153, 0, 0));
        Checkkkout.setColorSelForeground(new java.awt.Color(140, 140, 140));
        Checkkkout.setColorTextDiaActual(new java.awt.Color(140, 140, 140));
        Checkkkout.setPlaceholder(" Check-out Date...");
        jPanel1.add(Checkkkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 360, 40));

        Checkin.setBackground(new java.awt.Color(140, 140, 140));
        Checkin.setColorBackground(new java.awt.Color(153, 0, 0));
        Checkin.setColorButtonHover(new java.awt.Color(153, 0, 0));
        Checkin.setColorForeground(new java.awt.Color(153, 0, 0));
        Checkin.setColorSelForeground(new java.awt.Color(140, 140, 140));
        Checkin.setColorTextDiaActual(new java.awt.Color(140, 140, 140));
        Checkin.setPlaceholder(" Check-in Date...");
        jPanel1.add(Checkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 360, 40));

        ReserveRoom.setBackground(new java.awt.Color(78, 52, 46));
        ReserveRoom.setText("Reserve Room");
        ReserveRoom.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        ReserveRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveRoomActionPerformed(evt);
            }
        });
        jPanel1.add(ReserveRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 670, 230, 60));

        ComputeTotalbtn.setBackground(new java.awt.Color(78, 52, 46));
        ComputeTotalbtn.setText("Compute Total");
        ComputeTotalbtn.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        ComputeTotalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputeTotalbtnActionPerformed(evt);
            }
        });
        jPanel1.add(ComputeTotalbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 670, 220, 60));

        CustomerNametxt.setText(" ");
        CustomerNametxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        CustomerNametxt.setPlaceholder(" Enter Customer Name...");
        CustomerNametxt.setSelectionColor(new java.awt.Color(153, 0, 0));
        jPanel1.add(CustomerNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 320, 40));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel12.setText("Total Stay Price:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 650, 150, -1));

        roomtypetxt.setText(" ");
        roomtypetxt.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        roomtypetxt.setPlaceholder("Enter Room No...");
        roomtypetxt.setSelectionColor(new java.awt.Color(153, 0, 0));
        jPanel1.add(roomtypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, 320, 40));

        roomnotxt1.setText(" ");
        roomnotxt1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        roomnotxt1.setPlaceholder("Enter Room No...");
        roomnotxt1.setSelectionColor(new java.awt.Color(153, 0, 0));
        jPanel1.add(roomnotxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 320, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1375, 856));

        setSize(new java.awt.Dimension(1375, 856));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        AllRoomsD rooms = new AllRoomsD();
        rooms.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void ReserveRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveRoomActionPerformed
        // TODO add your handling code here:
        if (validateReservationFields()) {
            // Collect data from the reservation form
            String customerName = CustomerNametxt.getText();

            // Get the date values from JDateChooser
            java.util.Date checkInDateUtil = Checkin.getDatoFecha(); // Assuming txtCheckInDate is a JDateChooser
            java.util.Date checkOutDateUtil = Checkkkout.getDatoFecha(); // Assuming txtCheckOutDate is a JDateChooser

            // Convert java.util.Date to java.sql.Date
            java.sql.Date checkInDate = new java.sql.Date(checkInDateUtil.getTime());
            java.sql.Date checkOutDate = new java.sql.Date(checkOutDateUtil.getTime());

            // Get the room type from text field
            String roomType = roomtypetxt.getText().trim(); // Assuming txtRoomType is a JTextField

            // Get the room number from text field  
            String roomNumberText = roomnotxt1.getText().trim(); // Assuming txtRoomNumber is a JTextField

            // Ensure the original price and discounted price fields are not empty
            String totalPriceText = totalStayPricetxt.getText();

            double totalPrice = 0.0;
            if (!totalPriceText.isEmpty()) {
                // Remove non-numeric characters, like "PKR" and commas
                totalPriceText = totalPriceText.replaceAll("[^0-9.]", "");
                try {
                    totalPrice = Double.parseDouble(totalPriceText);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Invalid price format.", "Input Error", JOptionPane.ERROR_MESSAGE);
                    return; // Exit the method to prevent further issues
                }
            }

            // Create a new Payment instance and pass the collected data
            MakePayment paymentPage = new MakePayment(customerName, checkInDate, checkOutDate, roomNumberText, roomType, totalPrice);
            paymentPage.setVisible(true);

            // Optionally, close the Reservation page
            this.dispose();
        } else {
            // If validation fails, show an error message or handle it accordingly
            JOptionPane.showMessageDialog(this, "Please fill in all required fields correctly.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ReserveRoomActionPerformed

    private void ComputeTotalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputeTotalbtnActionPerformed
        // TODO add your handling code here:
        if (validateReservationFields()) {
            calculateTotalPrice(); // Calculate original price

        }

    }//GEN-LAST:event_ComputeTotalbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeReservations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSDateChooser Checkin;
    private rojeru_san.componentes.RSDateChooser Checkkkout;
    private necesario.RSMaterialButtonCircle ComputeTotalbtn;
    private app.bolivia.swing.JCTextField CustomerNametxt;
    private necesario.RSMaterialButtonCircle ReserveRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private app.bolivia.swing.JCTextField roomnotxt1;
    private app.bolivia.swing.JCTextField roomtypetxt;
    private app.bolivia.swing.JCTextField totalStayPricetxt;
    // End of variables declaration//GEN-END:variables
}
