/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hotel_Reservation_System;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ukasha Gamer
 */
public class ViewBookings extends javax.swing.JFrame {

    /**
     * Creates new form BookingDetails
     */
    public ViewBookings() {
        initComponents();
        setReservationDataToTable();
    }

    DefaultTableModel model;

     public void setReservationDataToTable() {
        try {
            
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from reservations");

            while (rs.next()) {
                String Id = rs.getString("id");
                String name = rs.getString("customer_name");
                String checkIn = rs.getString("check_in_date");
                String checkOut = rs.getString("check_out_date");
                String roomNo = rs.getString("room_number");
                String roomType = rs.getString("room_type");
                String price = rs.getString("total_price");

                String paymentMethod = rs.getString("payment_method");
                String status = rs.getString("payment_status");

                Object obj[] = {Id, name, checkIn, checkOut, roomNo, roomType, price,
                    paymentMethod, status};
                model = (DefaultTableModel) tblBooking.getModel();
                model.addRow(obj);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }     
    
 
    private void refreshData() {
        // Clear existing data in the table
        DefaultTableModel model = (DefaultTableModel) tblBooking.getModel();
        model.setRowCount(0);

        // Re-fetch and display updated data
        setReservationDataToTable();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooking = new rojeru_san.complementos.RSTableMetro();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        searchbtn = new necesario.RSMaterialButtonCircle();
        jCTextField2 = new app.bolivia.swing.JCTextField();
        customerNametxt = new app.bolivia.swing.JCTextField();
        REFERESHBTN = new necesario.RSMaterialButtonCircle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 240, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Booking Overview");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 540, 60));

        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(2285, 123, 348, 26));

        jLabel5.setFont(new java.awt.Font("Serif", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("- Ensure your reservation details are correct before your visit");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 450, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 38, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel2.setText(" ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 60, -1));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel7.setText(" ");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 60, -1));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/icons8_Rewind_48px.png"))); // NOI18N
        jLabel8.setText(" ");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 60, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1368, 200));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 1368, 30));

        tblBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RESERVATION ID", "CUSTOMER NAME", "CHECK-IN", "CHECK-OUT", "ROOM NO", "ROOM TYPE", "PRICE", "PAYMENT METHOD", "PAYMENT STATUS"
            }
        ));
        tblBooking.setColorBackgoundHead(new java.awt.Color(51, 0, 0));
        tblBooking.setColorFilasBackgound2(new java.awt.Color(139, 69, 19));
        tblBooking.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblBooking.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblBooking.setColorSelBackgound(new java.awt.Color(0, 0, 0));
        tblBooking.setFuenteFilas(new java.awt.Font("Serif", 1, 18)); // NOI18N
        tblBooking.setFuenteHead(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        tblBooking.setRowHeight(25);
        jScrollPane1.setViewportView(tblBooking);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 1320, 320));

        jPanel5.setBackground(new java.awt.Color(250, 240, 230));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel4.setText(" Customer Name:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 162, 23));

        searchbtn.setBackground(new java.awt.Color(0, 0, 0));
        searchbtn.setText(" Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel5.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 170, 44));

        jCTextField2.setText(" ");
        jCTextField2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCTextField2.setPlaceholder(" Enter Customer Name...");
        jCTextField2.setSelectionColor(new java.awt.Color(153, 0, 0));
        jPanel5.add(jCTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 320, 30));

        customerNametxt.setText(" ");
        customerNametxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customerNametxt.setPlaceholder(" Enter Customer Name...");
        customerNametxt.setSelectionColor(new java.awt.Color(153, 0, 0));
        jPanel5.add(customerNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 290, 40));

        REFERESHBTN.setBackground(new java.awt.Color(0, 0, 0));
        REFERESHBTN.setText("refresh");
        REFERESHBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REFERESHBTNActionPerformed(evt);
            }
        });
        jPanel5.add(REFERESHBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 160, 44));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 1080, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1375, 856));

        setBounds(0, 0, 1375, 856);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        DashBoard db = new DashBoard();
        db.setVisible(true);
        dispose();
        //this.setVisible(false); // Hide the current frame instead of disposing it
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel8MouseClicked

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        String customerName = customerNametxt.getText().trim(); // Get the text entered by the user
        model = (DefaultTableModel) tblBooking.getModel();
        model.setRowCount(0); // Clear existing rows

        String query = "SELECT * FROM reservations";

        // Add a WHERE clause if a name is entered
        if (!customerName.isEmpty()) {
            query += " WHERE customer_name LIKE ?";
        }

        try (Connection con = DBConnection.getConnection(); PreparedStatement pst = con.prepareStatement(query)) {

            // Set the parameter if a name is entered
            if (!customerName.isEmpty()) {
                pst.setString(1, "%" + customerName + "%"); // Use wildcard for partial matches
            }

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String Id = rs.getString("id");
                String name = rs.getString("customer_name");
                String checkIn = rs.getString("check_in_date");
                String checkOut = rs.getString("check_out_date");
                String roomNo = rs.getString("room_number");
                String roomType = rs.getString("room_type");
                String price = rs.getString("total_price");

                String paymentMethod = rs.getString("payment_method");
                String status = rs.getString("payment_status");

                Object obj[] = {Id, name, checkIn, checkOut, roomNo, roomType, price, paymentMethod, status};
                model.addRow(obj);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }   
     
    }//GEN-LAST:event_searchbtnActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        System.exit(0);
        // this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void REFERESHBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REFERESHBTNActionPerformed
        // TODO add your handling code here:
        refreshData();
    }//GEN-LAST:event_REFERESHBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private necesario.RSMaterialButtonCircle REFERESHBTN;
    private app.bolivia.swing.JCTextField customerNametxt;
    private app.bolivia.swing.JCTextField jCTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private necesario.RSMaterialButtonCircle searchbtn;
    private rojeru_san.complementos.RSTableMetro tblBooking;
    // End of variables declaration//GEN-END:variables
}
